puts "Creating Positions..."
Position.create(name: "Starting Pitcher", abbreviation: "SP", scorebook_id: "1")
Position.create(name: "Relief Pitcher", abbreviation: "RP", scorebook_id: "1")
Position.create(name: "Catcher", abbreviation: "C", scorebook_id: "2")
Position.create(name: "First Base", abbreviation: "1B", scorebook_id: "3")
Position.create(name: "Second Base", abbreviation: "2B", scorebook_id: "4")
Position.create(name: "Third Base", abbreviation: "3B", scorebook_id: "5")
Position.create(name: "Shortstop", abbreviation: "SS", scorebook_id: "6")
Position.create(name: "Left Field", abbreviation: "LF", scorebook_id: "7")
Position.create(name: "Center Field", abbreviation: "CF", scorebook_id: "8")
Position.create(name: "Right Field", abbreviation: "RF", scorebook_id: "9")
Position.create(name: "Designated Hitter", abbreviation: "DH", scorebook_id: "DH")
