puts "Creating Teams..."
league = League.find_by(name: "American League")
division = Division.find_by(league: league, region: "East")
Team.create!(city: "Baltimore", name: "Orioles", division: division, logo: "orioles.png", abbreviation: "BAL")
Team.create!(city: "Boston", name: "Red Sox", division: division, logo: "red_sox.png", abbreviation: "BOS")
Team.create!(city: "New York", name: "Yankees", division: division, logo: "yankees.png", abbreviation: "NYY")
Team.create!(city: "Tampa Bay", name: "Rays", division: division, logo: "rays.png", abbreviation: "TB")
Team.create!(city: "Toronto", name: "Blue Jays", division: division, logo: "blue_jays.png", abbreviation: "TOR")

division = Division.find_by(league: league, region: "Central")
Team.create!(city: "Chicago", name: "White Sox", division: division, logo: "white_sox.png", abbreviation: "CHW")
Team.create!(city: "Cleveland", name: "Indians", division: division, logo: "indians.png", abbreviation: "CLE")
Team.create!(city: "Detroit", name: "Tigers", division: division, logo: "tigers.png", abbreviation: "DET")
Team.create!(city: "Kansas City", name: "Royals", division: division, logo: "royals.png", abbreviation: "KC")
Team.create!(city: "Minnesota", name: "Twins", division: division, logo: "twins.png", abbreviation: "MIN")

division = Division.find_by(league: league, region: "West")
Team.create!(city: "Houston", name: "Astros", division: division, logo: "astros.png", abbreviation: "HOU")
Team.create!(city: "Los Angeles", name: "Angels", division: division, logo: "angels.png", abbreviation: "LAA")
Team.create!(city: "Oakland", name: "Athletics", division: division, logo: "athletics.png", abbreviation: "OAK")
Team.create!(city: "Seattle", name: "Mariners", division: division, logo: "mariners.png", abbreviation: "SEA")
Team.create!(city: "Texas", name: "Rangers", division: division, logo: "rangers.png", abbreviation: "TEX")

league = League.find_by(name: "National League")
division = Division.find_by(league: league, region: "East")
Team.create!(city: "Atlanta", name: "Braves", division: division, logo: "braves.png", abbreviation: "ATL")
Team.create!(city: "Miami", name: "Marlins", division: division, logo: "marlins.png", abbreviation: "MIA")
Team.create!(city: "New York", name: "Mets", division: division, logo: "mets.png", abbreviation: "NYM")
Team.create!(city: "Philadelphia", name: "Phillies", division: division, logo: "phillies.gif", abbreviation: "PHI")
Team.create!(city: "Washington", name: "Nationals", division: division, logo: "nationals.png", abbreviation: "WSH")

division = Division.find_by(league: league, region: "Central")
Team.create!(city: "Chicago", name: "Cubs", division: division, logo: "cubs.png", abbreviation: "CHC")
Team.create!(city: "Cincinnati", name: "Reds", division: division, logo: "reds.gif", abbreviation: "CIN")
Team.create!(city: "Milwaukee", name: "Brewers", division: division, logo: "brewers.png", abbreviation: "MIL")
Team.create!(city: "Pittsburgh", name: "Pirates", division: division, logo: "pirates.png", abbreviation: "PIT")
Team.create!(city: "St. Louis", name: "Cardinals", division: division, logo: "cardinals.gif", abbreviation: "STL")

division = Division.find_by(league: league, region: "West")
Team.create!(city: "Arizona", name: "Diamondbacks", division: division, logo: "diamondbacks.png", abbreviation: "ARI")
Team.create!(city: "Colorado", name: "Rockies", division: division, logo: "rockies.png", abbreviation: "COL")
Team.create!(city: "Los Angeles", name: "Dodgers", division: division, logo: "dodgers.png", abbreviation: "LAD")
Team.create!(city: "San Diego", name: "Padres", division: division, logo: "padres.png", abbreviation: "SD")
Team.create!(city: "San Francisco", name: "Giants", division: division, logo: "giants.png", abbreviation: "SF")
