language: ruby
rvm:
  - 2.3.0
addons:
  postgresql: "9.4"
script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
  - bundle exec rake cucumber
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'CREATE DATABASE baseballsimulator_test;'  -U postgres
