development: &default
  adapter: postgresql
  encoding: unicode
  database: baseballsimulator_development
  host: localhost
  pool: 5
  username: baseballsimulator
  password: baseball

test: &test
  <<: *default
  database: baseballsimulator_test

cucumber:
  <<: *test
