development: &default
  adapter: postgresql
  encoding: unicode
  database: baseballsimulator_<%= Rails.env %>
  host: localhost
  pool: 5
  username: postgres
  password:

test: &test
  <<: *default
