development:
  adapter: postgresql
  encoding: unicode
  database: baseballsimulator_development
  host: localhost
  pool: 5
  username: baseballsimulator
  password: baseball

test:
  adapter: postgresql
  encoding: unicode
  database: baseballsimulator_test
  host: localhost
  pool: 5
  username: baseballsimulator
  password: baseball
